package org.imrofli.godfall.dao.model;

public enum ParameterTypeModel {
    ATTRIBUTE_NO_VARIANCE,
    CORE_ATTRIBUTE,
    CORE_ATTRIBUTE_PERCENT,
    DEFENSE_PERCENT,
    NON_SCALING,
    NO_VARIANCE_CORE_ATTRIBUTE_PERCENT,
    NO_VARIANCE_DEFENSE_PERCENT,
    NO_VARIANCE_PLAYER_POWER,
    PLAYER_POWER;

}
